sonar.organization=bamgcito
sonar.projectKey=bamgcito
sonar.projectName=Sistema Escolar - Proyecto Colegio

sonar.sources=ms-notas/src/main,ms-asistencia/src/main,ms-perfiles/src/main,ms-evaluaciones/src/main,ms-cursos/src/main,ms-asignatura/src/main

sonar.tests=ms-notas/src/test,ms-asistencia/src/test,ms-perfiles/src/test,ms-evaluaciones/src/test,ms-cursos/src/test

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=\
  ms-notas/target/site/jacoco/jacoco.xml,\
  ms-asistencia/target/site/jacoco/jacoco.xml,\
  ms-perfiles/target/site/jacoco/jacoco.xml,\
  ms-evaluaciones/target/site/jacoco/jacoco.xml,\
  ms-cursos/target/site/jacoco/jacoco.xml

sonar.exclusions=\
  **/*Application.java,\
  **/config/**,\
  **/security/**,\
  **/model/**,\
  **/dto/**,\
  **/repository/**
