spring.application.name=apigateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8090/eureka

jwt.secret=clave-secreta-super-segura-para-jwt-minimo-32-chars


spring.cloud.gateway.server.webmvc.routes[0].id=bff-auth-login
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/bff/auth/login
spring.cloud.gateway.server.webmvc.routes[0].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/bff/auth/login, /usuarios/login
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[1].id=bff-usuarios-listar
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/bff/usuarios
spring.cloud.gateway.server.webmvc.routes[1].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[1].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[2].id=bff-usuarios-crear
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/bff/usuarios
spring.cloud.gateway.server.webmvc.routes[2].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[2].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[3].id=bff-usuarios-crear-alumno
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/bff/usuarios/alumnos
spring.cloud.gateway.server.webmvc.routes[3].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[3].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[4].id=bff-usuarios-crear-profesor
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/bff/usuarios/profesores
spring.cloud.gateway.server.webmvc.routes[4].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[4].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[5].id=bff-usuarios-crear-apoderado
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/bff/usuarios/apoderados
spring.cloud.gateway.server.webmvc.routes[5].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[5].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[6].id=bff-usuarios-asociar-apoderado
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/bff/usuarios/alumnos/apoderados
spring.cloud.gateway.server.webmvc.routes[6].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[6].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[7].id=bff-usuarios-info-alumno
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/bff/usuarios/alumnos/{rut}/info
spring.cloud.gateway.server.webmvc.routes[7].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[7].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[7].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[8].id=bff-usuarios-alumno-por-id
spring.cloud.gateway.server.webmvc.routes[8].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/bff/usuarios/alumnos/id/{id}
spring.cloud.gateway.server.webmvc.routes[8].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[8].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[9].id=bff-usuarios-profesor-por-id
spring.cloud.gateway.server.webmvc.routes[9].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/bff/usuarios/profesores/{id}
spring.cloud.gateway.server.webmvc.routes[9].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[9].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


spring.cloud.gateway.server.webmvc.routes[10].id=bff-cursos-listar
spring.cloud.gateway.server.webmvc.routes[10].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/bff/cursos
spring.cloud.gateway.server.webmvc.routes[10].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[10].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[10].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[11].id=bff-cursos-crear
spring.cloud.gateway.server.webmvc.routes[11].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/bff/cursos
spring.cloud.gateway.server.webmvc.routes[11].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[11].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[11].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[12].id=bff-cursos-asignar-alumno
spring.cloud.gateway.server.webmvc.routes[12].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[12].predicates[0]=Path=/bff/cursos/alumnos
spring.cloud.gateway.server.webmvc.routes[12].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[12].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[12].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[13].id=bff-cursos-profesor-jefe
spring.cloud.gateway.server.webmvc.routes[13].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[13].predicates[0]=Path=/bff/cursos/{id}/profesor-jefe
spring.cloud.gateway.server.webmvc.routes[13].predicates[1]=Method=PUT
spring.cloud.gateway.server.webmvc.routes[13].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[13].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


spring.cloud.gateway.server.webmvc.routes[14].id=bff-academico-asignaturas-listar
spring.cloud.gateway.server.webmvc.routes[14].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[14].predicates[0]=Path=/bff/academico/asignaturas
spring.cloud.gateway.server.webmvc.routes[14].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[14].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[14].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[15].id=bff-academico-asignaturas-crear
spring.cloud.gateway.server.webmvc.routes[15].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[15].predicates[0]=Path=/bff/academico/asignaturas
spring.cloud.gateway.server.webmvc.routes[15].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[15].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[15].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[16].id=bff-academico-asignaciones-por-curso
spring.cloud.gateway.server.webmvc.routes[16].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[16].predicates[0]=Path=/bff/academico/asignaciones/curso/{cursoId}
spring.cloud.gateway.server.webmvc.routes[16].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[16].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[16].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[17].id=bff-academico-asignacion-por-id
spring.cloud.gateway.server.webmvc.routes[17].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[17].predicates[0]=Path=/bff/academico/asignaciones/{id}
spring.cloud.gateway.server.webmvc.routes[17].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[17].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[17].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[18].id=bff-academico-asignaciones-crear
spring.cloud.gateway.server.webmvc.routes[18].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[18].predicates[0]=Path=/bff/academico/asignaciones
spring.cloud.gateway.server.webmvc.routes[18].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[18].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[18].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[19].id=bff-academico-evaluaciones-por-asignacion
spring.cloud.gateway.server.webmvc.routes[19].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[19].predicates[0]=Path=/bff/academico/evaluaciones/asignacion/{asignacionId}
spring.cloud.gateway.server.webmvc.routes[19].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[19].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[19].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[20].id=bff-academico-evaluaciones-crear
spring.cloud.gateway.server.webmvc.routes[20].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[20].predicates[0]=Path=/bff/academico/evaluaciones
spring.cloud.gateway.server.webmvc.routes[20].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[20].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[20].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[21].id=bff-academico-notas-alumno
spring.cloud.gateway.server.webmvc.routes[21].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[21].predicates[0]=Path=/bff/academico/notas/alumno
spring.cloud.gateway.server.webmvc.routes[21].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[21].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[21].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[22].id=bff-academico-notas-promedio
spring.cloud.gateway.server.webmvc.routes[22].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[22].predicates[0]=Path=/bff/academico/notas/alumno/promedio
spring.cloud.gateway.server.webmvc.routes[22].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[22].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[22].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[23].id=bff-academico-notas-por-evaluacion
spring.cloud.gateway.server.webmvc.routes[23].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[23].predicates[0]=Path=/bff/academico/notas/evaluacion/{evaluacionId}
spring.cloud.gateway.server.webmvc.routes[23].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[23].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[23].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[24].id=bff-academico-notas-crear
spring.cloud.gateway.server.webmvc.routes[24].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[24].predicates[0]=Path=/bff/academico/notas
spring.cloud.gateway.server.webmvc.routes[24].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[24].filters[0]=RewritePath=/bff/academico/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[24].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


spring.cloud.gateway.server.webmvc.routes[25].id=bff-asistencia-por-alumno
spring.cloud.gateway.server.webmvc.routes[25].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[25].predicates[0]=Path=/bff/asistencia/alumno/{rut}
spring.cloud.gateway.server.webmvc.routes[25].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[25].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[25].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[26].id=bff-asistencia-porcentaje-alumno
spring.cloud.gateway.server.webmvc.routes[26].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[26].predicates[0]=Path=/bff/asistencia/alumno/{rut}/porcentaje
spring.cloud.gateway.server.webmvc.routes[26].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[26].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[26].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[27].id=bff-asistencia-por-asignacion
spring.cloud.gateway.server.webmvc.routes[27].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[27].predicates[0]=Path=/bff/asistencia/asignacion/{asignacionId}
spring.cloud.gateway.server.webmvc.routes[27].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[27].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[27].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[28].id=bff-asistencia-registrar
spring.cloud.gateway.server.webmvc.routes[28].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[28].predicates[0]=Path=/bff/asistencia
spring.cloud.gateway.server.webmvc.routes[28].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[28].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[28].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[29].id=bff-anotaciones-por-alumno
spring.cloud.gateway.server.webmvc.routes[29].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[29].predicates[0]=Path=/bff/asistencia/anotaciones/alumno/{rut}
spring.cloud.gateway.server.webmvc.routes[29].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[29].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[29].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[30].id=bff-anotaciones-por-asignacion
spring.cloud.gateway.server.webmvc.routes[30].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[30].predicates[0]=Path=/bff/asistencia/anotaciones/asignacion/{asignacionId}
spring.cloud.gateway.server.webmvc.routes[30].predicates[1]=Method=GET
spring.cloud.gateway.server.webmvc.routes[30].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[30].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[31].id=bff-anotaciones-registrar
spring.cloud.gateway.server.webmvc.routes[31].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[31].predicates[0]=Path=/bff/asistencia/anotaciones
spring.cloud.gateway.server.webmvc.routes[31].predicates[1]=Method=POST
spring.cloud.gateway.server.webmvc.routes[31].filters[0]=RewritePath=/bff/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[31].filters[1]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin