eureka.client.service-url.defaultZone=http://eureka-server:8090/eureka/

# ── MICROSERVICIOS (/bff/ms/**) ──────────────────────────────────────
spring.cloud.gateway.server.webmvc.routes[0].id=bff-ms-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/bff/ms/auth/**
spring.cloud.gateway.server.webmvc.routes[0].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[1].id=bff-ms-usuarios
spring.cloud.gateway.server.webmvc.routes[1].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/bff/ms/usuarios/**
spring.cloud.gateway.server.webmvc.routes[1].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[2].id=bff-ms-roles
spring.cloud.gateway.server.webmvc.routes[2].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/bff/ms/roles/**
spring.cloud.gateway.server.webmvc.routes[2].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[3].id=bff-ms-perfiles
spring.cloud.gateway.server.webmvc.routes[3].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/bff/ms/perfiles/**
spring.cloud.gateway.server.webmvc.routes[3].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[4].id=bff-ms-cursos
spring.cloud.gateway.server.webmvc.routes[4].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/bff/ms/cursos/**
spring.cloud.gateway.server.webmvc.routes[4].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[5].id=bff-ms-asignaturas
spring.cloud.gateway.server.webmvc.routes[5].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/bff/ms/asignaturas/**
spring.cloud.gateway.server.webmvc.routes[5].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[6].id=bff-ms-asignaciones
spring.cloud.gateway.server.webmvc.routes[6].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/bff/ms/asignaciones/**
spring.cloud.gateway.server.webmvc.routes[6].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[7].id=bff-ms-evaluaciones
spring.cloud.gateway.server.webmvc.routes[7].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/bff/ms/evaluaciones/**
spring.cloud.gateway.server.webmvc.routes[7].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[7].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[8].id=bff-ms-notas
spring.cloud.gateway.server.webmvc.routes[8].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/bff/ms/notas/**
spring.cloud.gateway.server.webmvc.routes[8].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[9].id=bff-ms-asistencia
spring.cloud.gateway.server.webmvc.routes[9].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/bff/ms/asistencia/**
spring.cloud.gateway.server.webmvc.routes[9].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[10].id=bff-ms-anotaciones
spring.cloud.gateway.server.webmvc.routes[10].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/bff/ms/anotaciones/**
spring.cloud.gateway.server.webmvc.routes[10].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[10].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[11].id=bff-ms-comunicacion
spring.cloud.gateway.server.webmvc.routes[11].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/bff/ms/comunicacion/**
spring.cloud.gateway.server.webmvc.routes[11].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[11].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[12].id=bff-ms-certificados
spring.cloud.gateway.server.webmvc.routes[12].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[12].predicates[0]=Path=/bff/ms/certificados/**
spring.cloud.gateway.server.webmvc.routes[12].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[12].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.server.webmvc.routes[13].id=bff-ms-horarios
spring.cloud.gateway.server.webmvc.routes[13].uri=http://bff:8091
spring.cloud.gateway.server.webmvc.routes[13].predicates[0]=Path=/bff/ms/horarios/**
spring.cloud.gateway.server.webmvc.routes[13].predicates[1]=Method=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.server.webmvc.routes[13].filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

