spring.application.name=AUTH-SERVICE
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8090/eureka

jwt.secret=clave-secreta-super-segura-para-jwt-minimo-32-chars
jwt.expiration=86400000
