spring.application.name=BFF
server.port=8091

eureka.client.service-url.defaultZone=http://localhost:8090/eureka
eureka.instance.prefer-ip-address=true

ms.msauth=http://AUTH-SERVICE
ms.msusuarios=http://MS-USUARIOS
ms.msperfiles=http://MS-PERFILES
ms.mscursos=http://MS-CURSOS
ms.msasignaturas=http://MS-ASIGNATURAS
ms.msevaluaciones=http://MS-EVALUACIONES
ms.msnotas=http://MS-NOTAS
ms.msasistencia=http://MS-ASISTENCIA
ms.mscomunicacion=http://localhost:3000
ms.mscertificados=http://MS-CERTIFICADOS
ms.mshorarios=http://MS-HORARIOS

server.tomcat.connection-timeout=20000
spring.mvc.async.request-timeout=20000
