spring.application.name=BFF
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8090/eureka
eureka.instance.prefer-ip-address=true

ms.usuarios=http://GESTIONUSUARIO
ms.cursos=http://GESTIONCURSO
ms.academico=http://GESTIONACADEMICO
ms.asistencia=http://GESTIONASISTENCIA

server.tomcat.connection-timeout=20000
spring.mvc.async.request-timeout=20000
